# Generated by Django 2.2.3 on 2019-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='price',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
